export const styles = {
  page: 'p-6 max-w-5xl mx-auto flex flex-col items-center justify-center min-h-[60vh]',
  title: 'text-2xl font-bold text-gray-900 self-start mb-16 w-full',
  style: 'flex flex-col items-center',
  style2: 'w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mb-4',
  icon: 'w-8 h-8 text-gray-400',
  sectionTitle: 'text-lg font-semibold text-gray-900 mb-2',
  mutedText: 'text-gray-500 mb-6 text-sm',
  primaryButton: 'bg-teal-600 hover:bg-teal-700 text-white font-medium px-6 py-2.5 rounded-lg transition-colors',
  page2: 'p-6 max-w-5xl mx-auto',
  style3: 'flex items-center justify-between mb-6',
  title2: 'text-2xl font-bold text-gray-900',
  style4: 'text-sm text-red-500 hover:text-red-600 font-medium transition-colors',
  panel: 'bg-white border border-gray-200 rounded-xl mb-6 overflow-hidden shadow-sm',
  style5: 'divide-y divide-gray-200',
  style6: 'p-6 flex items-center flex-col sm:flex-row gap-6',
  style7: 'w-20 h-20 bg-gray-50 rounded-lg flex items-center justify-center flex-shrink-0 border border-gray-100',
  style8: 'text-[10px] text-gray-400',
  style9: 'flex-1 min-w-0',
  style10: 'text-base font-medium text-gray-900 hover:text-teal-600 truncate block',
  mutedText2: 'text-sm text-gray-500 mt-1',
  style11: 'flex items-center gap-6 w-full sm:w-auto justify-between sm:justify-end',
  icon2: 'flex items-center border border-gray-300 rounded-lg h-9 w-28',
  style12: 'flex-1 flex items-center justify-center text-gray-500 hover:text-gray-900 disabled:opacity-50',
  icon3: 'w-3.5 h-3.5',
  style13: 'w-8 text-center text-sm font-medium text-gray-900',
  style14: 'text-base font-bold text-gray-900 w-20 text-right',
  style15: 'p-2 text-gray-400 hover:text-red-500 transition-colors rounded-lg hover:bg-red-50',
  icon4: 'w-5 h-5',
  panel2: 'bg-white border border-gray-200 rounded-xl p-6 shadow-sm',
  style16: 'text-gray-600 font-medium',
  primaryButton2: 'w-full bg-teal-600 hover:bg-teal-700 text-white font-medium py-3 rounded-lg transition-colors text-base',
};
