export const styles = {
  style: 'p-6 text-center',
  style2: 'text-gray-500',
  primaryButton: 'text-teal-600 hover:underline mt-2',
  page: 'p-6 max-w-4xl mx-auto',
  mutedText: 'flex items-center text-sm text-gray-500 hover:text-gray-900 mb-6 transition-colors',
  icon: 'w-4 h-4 mr-1',
  style3: 'flex justify-between items-start mb-6',
  title: 'text-2xl font-bold text-gray-900',
  style4: 'text-sm text-gray-400 mt-1',
  style5: 'px-3 py-1 bg-blue-50 text-blue-600 text-sm font-medium rounded-full',
  panel: 'bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden mb-6',
  style6: 'p-6',
  style7: 'text-sm font-semibold text-gray-900 uppercase tracking-wider mb-4 text-gray-400',
  style8: 'divide-y divide-gray-100',
  style9: 'py-3 flex justify-between text-sm',
  style10: 'text-gray-800',
  style11: 'text-gray-400 text-xs',
  style12: 'font-medium text-gray-900',
  style13: 'border-t border-gray-100 mt-4 pt-4 flex justify-between items-center font-bold text-gray-900',
  style14: 'text-lg',
  panel2: 'bg-white border border-gray-200 rounded-xl shadow-sm p-6 mb-6',
  style15: 'grid grid-cols-1 md:grid-cols-2 gap-4 text-sm mb-4',
  style16: 'text-gray-900 font-medium mt-0.5',
  page2: 'text-sm space-y-4',
  style17: 'text-gray-600 mt-0.5',
  panel3: 'bg-white border border-gray-200 rounded-xl shadow-sm p-6',
  style18: 'flex items-center gap-2 mb-6',
  mutedText2: 'text-sm text-gray-500',
  style19: 'px-2.5 py-0.5 bg-blue-50 text-blue-600 text-xs font-medium rounded-full',
  style20: 'relative border-l-2 border-teal-500 pl-4 ml-2 pb-2',
  style21: 'absolute -left-[7px] top-1.5 w-3 h-3 rounded-full bg-teal-500 border border-white',
  style22: 'text-sm font-medium text-gray-900',
  style23: 'text-xs text-gray-400 mt-0.5',
  style24: 'text-center text-[11px] text-gray-400 mt-8',
};
