export const styles = {
  page: 'space-y-8',
  header: 'flex flex-col gap-2',
  eyebrow: 'text-sm font-medium text-teal-700',
  title: 'text-2xl font-bold text-gray-900',
  subtitle: 'text-sm text-gray-500',
  statsGrid: 'grid gap-4 sm:grid-cols-2 xl:grid-cols-5',
  statCard: 'rounded-lg border border-gray-200 bg-white p-5 shadow-sm',
  statTop: 'flex items-center justify-between gap-4',
  statLabel: 'text-sm font-medium text-gray-500',
  statValue: 'mt-3 text-3xl font-bold text-gray-900',
  statIcon: 'flex h-10 w-10 items-center justify-center rounded-lg border',
  statSvg: 'h-5 w-5',
  tealTone: 'border-teal-100 bg-teal-50 text-teal-700',
  blueTone: 'border-blue-100 bg-blue-50 text-blue-700',
  emeraldTone: 'border-emerald-100 bg-emerald-50 text-emerald-700',
  amberTone: 'border-amber-100 bg-amber-50 text-amber-700',
  purpleTone: 'border-purple-100 bg-purple-50 text-purple-700',
  sectionTitle: 'text-lg font-semibold text-gray-900',
  actionsGrid: 'mt-4 grid gap-4 md:grid-cols-3',
  actionCard:
    'flex min-h-32 items-center justify-between rounded-lg border border-gray-200 bg-white p-5 shadow-sm transition-colors hover:border-teal-300 hover:bg-teal-50',
  actionTitle: 'font-semibold text-gray-900',
  actionText: 'mt-1 text-sm text-gray-500',
  actionIcon: 'h-6 w-6 flex-none text-teal-600',
};
