export const styles = {
  page: 'p-6 max-w-4xl mx-auto',
  title: 'text-2xl font-bold text-gray-900 mb-6',
  panel: 'bg-white border border-gray-200 rounded-xl mb-6 shadow-sm overflow-hidden',
  style: 'p-6',
  sectionTitle: 'text-lg font-semibold text-gray-900 mb-4',
  page2: 'space-y-3 mb-4',
  style2: 'flex justify-between text-sm text-gray-600',
  style3: 'font-medium',
  style4: 'border-t border-gray-100 pt-4 flex justify-between items-center',
  style5: 'text-base font-bold text-gray-900',
  style6: 'text-xl font-bold text-gray-900',
  panel2: 'bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden',
  sectionTitle2: 'text-lg font-semibold text-gray-900 mb-1',
  mutedText: 'text-sm text-gray-500 mb-6',
  page3: 'space-y-5',
  style7: 'block text-sm font-medium text-gray-700 mb-1',
  required: 'text-red-500',
  mutedText2: 'w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-50 text-gray-500 cursor-not-allowed sm:text-sm',
  input: 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-1 focus:ring-teal-500 focus:border-teal-500 sm:text-sm',
  input2: 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-1 focus:ring-teal-500 focus:border-teal-500 sm:text-sm resize-none',
  primaryButton: 'w-full bg-teal-600 hover:bg-teal-700 text-white font-medium py-3 rounded-lg transition-colors text-base mt-2',
};
