export const styles = {
  style: 'flex flex-col items-center justify-center min-h-[50vh]',
  title: 'text-2xl font-bold text-gray-700 mb-4',
  primaryButton: 'text-teal-600 hover:underline',
  page: 'p-6 max-w-7xl mx-auto',
  style2: 'flex items-center text-gray-500 hover:text-gray-900 mb-6 transition-colors',
  icon: 'w-4 h-4 mr-2',
  panel: 'bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden flex flex-col md:flex-row min-h-[500px]',
  style3: 'md:w-1/2 bg-gray-50 relative flex items-center justify-center min-h-[300px] border-r border-gray-100',
  style4: 'text-4xl text-gray-300 font-medium tracking-wider',
  style5: 'md:w-1/2 p-8 md:p-12 flex flex-col',
  style6: 'mb-4',
  style7: 'inline-block px-3 py-1 bg-teal-50 text-teal-600 text-xs font-medium rounded-full',
  title2: 'text-3xl font-bold text-gray-900 mb-4',
  style8: 'mb-6 pb-6 border-b border-gray-100',
  title3: 'text-3xl font-bold text-gray-900',
  stockStatus: 'mt-2 text-sm font-medium',
  inStock: 'text-teal-600',
  outOfStock: 'text-red-500',
  style9: 'mb-8 flex-1',
  style10: 'text-sm font-semibold text-gray-900 mb-2',
  style11: 'text-gray-600 leading-relaxed text-sm',
  style12: 'mt-auto',
  style13: 'mb-6',
  style14: 'text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1',
  style15: 'text-sm text-gray-900',
  style16: 'flex items-center gap-4',
  icon2: 'flex items-center border border-gray-300 rounded-lg h-11 w-32',
  style17: 'flex-1 flex items-center justify-center text-gray-500 hover:text-gray-900 disabled:opacity-50',
  icon3: 'w-4 h-4',
  style18: 'w-10 text-center font-medium text-gray-900',
  primaryButton2: 'flex-1 bg-teal-600 hover:bg-teal-700 text-white font-medium h-11 rounded-lg transition-colors disabled:bg-gray-300 disabled:cursor-not-allowed',
  errorToast: 'border border-red-500 px-4 py-3 text-gray-800 shadow-sm',
  successToast: 'border border-teal-500 px-4 py-3 text-gray-800 shadow-md',
};
