export const styles = {
  page: 'p-6 max-w-7xl mx-auto',
  style: 'mb-8',
  title: 'text-2xl font-bold text-gray-900 mb-1',
  mutedText: 'text-gray-500 text-sm',
  style2: 'relative mb-8',
  style3: 'absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none',
  icon: 'h-5 w-5 text-gray-400',
  input: 'block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-lg leading-5 bg-white placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-teal-500 focus:border-teal-500 sm:text-sm transition duration-150 ease-in-out',
  style4: 'flex flex-col md:flex-row gap-6',
  style5: 'w-full md:w-64 flex-shrink-0',
  panel: 'bg-white border border-gray-200 rounded-lg p-5',
  style6: 'text-sm font-semibold text-gray-900 mb-4',
  page2: 'space-y-3',
  style7: 'block text-xs font-medium text-gray-700',
  input2: 'mt-1 block w-full pl-3 pr-10 py-2 text-sm border-gray-300 focus:outline-none focus:ring-teal-500 focus:border-teal-500 rounded-md',
  style8: 'flex-1',
  style9: 'text-center py-12 text-gray-500',
  style10: 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6',
  panel2: 'bg-white border border-gray-200 rounded-xl overflow-hidden hover:shadow-lg transition-shadow duration-300 flex flex-col group',
  style11: 'aspect-w-1 aspect-h-1 bg-gray-100 relative overflow-hidden h-48',
  style12: 'absolute inset-0 flex items-center justify-center text-gray-400 font-medium group-hover:scale-105 transition-transform duration-300',
  style13: 'p-5 flex-1 flex flex-col',
  style14: 'text-xs text-gray-500 mb-1',
  style15: 'text-sm font-semibold text-gray-900 mb-4 line-clamp-2',
  style16: 'mt-auto flex items-center justify-between',
  style17: 'text-lg font-bold text-gray-900',
  stockStatus: 'text-xs font-medium',
  inStock: 'text-teal-600',
  outOfStock: 'text-red-500',
};
