export const styles = {
  page: 'min-h-screen bg-gray-50 flex flex-col justify-center items-center py-12 px-4 sm:px-6 lg:px-8',
  panel: 'max-w-md w-full bg-white p-8 border border-gray-200 rounded-xl shadow-sm',
  style: 'text-center mb-6',
  title: 'text-2xl font-bold text-gray-900',
  mutedText: 'text-sm text-gray-500 mt-1',
  primaryButton: 'text-teal-600 hover:text-teal-500 font-medium',
  style2: 'mb-4 text-sm text-red-600 bg-red-50 p-2.5 rounded-lg',
  page2: 'space-y-4',
  style3: 'block text-sm font-medium text-gray-700 mb-1',
  required: 'text-red-500',
  input: 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-500 focus:border-teal-500 text-sm',
  style4: 'text-xs text-gray-500 leading-relaxed pt-1',
  primaryButton2: 'w-full py-2.5 px-4 bg-teal-600 hover:bg-teal-700 text-white font-medium rounded-lg text-sm transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500 disabled:opacity-50 mt-2',
};
