export const styles = {
  page: 'space-y-8',
  header: 'flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between',
  eyebrow: 'text-sm font-medium text-teal-700',
  title: 'mt-1 text-2xl font-bold text-gray-900',
  subtitle: 'mt-1 text-sm text-gray-500',
  addButton:
    'inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-teal-600 px-4 text-sm font-medium text-white transition-colors hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-teal-500 focus:ring-offset-2',
  addButtonIcon: 'h-4 w-4',
  section: 'space-y-4',
  sectionHeader: 'flex items-center justify-between gap-3',
  sectionTitleWrap: 'flex items-center gap-3',
  sectionTitle: 'text-lg font-semibold text-gray-900',
  sectionIcon: 'h-5 w-5 text-teal-600',
  count: 'rounded-full bg-gray-100 px-2.5 py-1 text-xs font-medium text-gray-600',
  grid: 'grid gap-4 md:grid-cols-2 xl:grid-cols-3',
  card: 'overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm transition-colors hover:border-teal-300',
  cardInactive: 'bg-gray-50 opacity-80 hover:border-gray-300',
  cardLink: 'block text-left',
  image: 'flex aspect-[4/3] w-full items-center justify-center bg-gray-100 text-gray-300',
  imageIcon: 'h-12 w-12',
  body: 'space-y-4 p-4',
  top: 'flex items-start justify-between gap-3',
  name: 'text-base font-semibold text-gray-900',
  category: 'mt-1 text-sm text-gray-500',
  price: 'text-base font-semibold text-gray-900',
  meta: 'grid grid-cols-2 gap-3 text-sm',
  metaLabel: 'text-gray-500',
  metaValue: 'mt-1 font-medium text-gray-900',
  actions: 'flex items-center justify-between gap-3 border-t border-gray-100 pt-4',
  editButton:
    'inline-flex h-9 items-center justify-center gap-2 rounded-lg border border-gray-300 px-3 text-sm font-medium text-gray-700 transition-colors hover:border-teal-300 hover:bg-teal-50 hover:text-teal-700',
  editIcon: 'h-4 w-4',
  status: 'inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium',
  statusActive: 'bg-emerald-50 text-emerald-700',
  statusInactive: 'bg-gray-200 text-gray-600',
  toggle:
    'inline-flex h-6 w-11 items-center rounded-full p-0.5 transition-colors focus:outline-none focus:ring-2 focus:ring-teal-500 focus:ring-offset-2',
  toggleActive: 'bg-teal-600',
  toggleInactive: 'bg-gray-300',
  thumb: 'h-5 w-5 rounded-full bg-white shadow-sm transition-transform',
  thumbActive: 'translate-x-5',
  empty: 'rounded-lg border border-dashed border-gray-300 bg-white p-8 text-center',
  emptyTitle: 'text-base font-semibold text-gray-900',
  emptyText: 'mt-1 text-sm text-gray-500',
};


